### PR TITLE
Nodejs 12.0 support

### PR DESCRIPTION
**Pull request by Smoozilla**
I'm no C++ pro hope this works, all tests passed

### CODE REVIEW

**Comment by jorangreef** [comment]
Thanks @Smoozilla 

If you can give me a bit of time, I will rather upgrade to N-API directly. Then we can drop the NAN dependency entirely.

**Comment by Smoozilla** [comment]
Yes that sounds much better, thanks for all your contributions!

**Comment by jorangreef** [comment]
Thanks @Smoozilla you too.

**Comment by Smoozilla** [comment]
@jorangreef I'm considering attempting this, figured I'd give you a heads up in case you already were working on it

**Comment by Smoozilla** [comment]
> @jorangreef I'm considering attempting this, figured I'd give you a heads up in case you already were working on it

I instead improved the rust port from your examples and have it running via wasm. Thank you for everything!

**Pull request closed without merging**
